### ISSUE TITLE
Unable to run examples in colab

### ISSUE THREAD

**Issue by MirekJan** [jadarve/lluvia#150]
I am trying to run the 'getting started' notebook in the google colab link and I am getting the following error

`
WARNING: Requirement 'bazel-bin/lluvia/python/lluvia-0.0.1-py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./bazel-bin/lluvia/python/lluvia-0.0.1-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/content/lluvia/bazel-bin/lluvia/python/lluvia-0.0.1-py3-none-any.whl'
`

**Comment by jadarve** [comment]
Hi, thanks for reporting the issue.

I'm able to reproduce the problem. It seems the vulkan SDK version used in the install scrip is outdated. I will work in a patch.

![image](https://github.com/jadarve/lluvia/assets/2498576/03753df1-bdf1-4d8d-a0fa-2f9fd89d30bf)

**Comment by jadarve** [comment]
I merged a patch to the master branch. Could you give it a try running the Colab notebook?

**Comment by MirekJan** [comment]
Thanks, the notebook builds fine.
