### ISSUE TITLE
Output looks off in Camera_Undistort notebook

### ISSUE THREAD

**Issue by MirekJan** [jadarve/lluvia#152]
<img width="1320" alt="Screenshot 2023-08-22 at 13 34 25" src="https://github.com/jadarve/lluvia/assets/6917117/29f3b286-c814-484e-82db-68bebc901047">

Please see the above image for issue.

**Comment by jadarve** [comment]
Hi, I guess you are referring to the [Camera undistort Colab notebook](https://colab.research.google.com/drive/1ZCuY7E904K7IdsI0FW2O13H_bYn-2LYJ). Indeed it's not giving the original results reported in the [blog post](https://lluvia.ai/blog/2022/09/18/camera-undistort/). I will take a look.

**Comment by MirekJan** [comment]
Thanks, will try a local build shortly.

**Comment by jadarve** [comment]
It seems as if the newer versions of the GPU runtime in Colab do not support the Vulkan driver. When I try to enumerate the available Vulkan devices in a T4 GPU runtime, all I get is the CPU device (using the Mesa driver). I will investigate further how to get Vulkan to work again in Colab.

**Comment by jadarve** [comment]
Related to this: https://github.com/googlecolab/colabtools/issues/3556

PR #160 solves the problem. The [colab notebook](https://colab.research.google.com/drive/1ZCuY7E904K7IdsI0FW2O13H_bYn-2LYJ) works again.

Let me know if it works for you so I can close this issue.

**Comment by jadarve** [comment]
Solved by #160
