### ISSUE TITLE
How do you build this? Please update readme

### ISSUE THREAD

**Issue by iplayfast** [jadarve/lluvia#154]
I see no Makefile,cmakelist.txt, setup.py, etc.
Yet in the samples there are cpp, and py and lua.

Could you explain how you make and use this software?

**Comment by jadarve** [comment]
Hi, the whole project is built as a single [Bazel project](https://bazel.build/). Long ago I used CMake but it was getting out of control combining C++ + Python + GLSL + Lua.

The build instructions for Ubuntu are here: https://lluvia.ai/docs/gettingstarted/installation/linux/

And the blog posts show some examples how to use it, mostly in Python: https://lluvia.ai/blog/

Documentation needs lots of work, any suggestion is welcome.
