### ISSUE TITLE
Is it possible calling Real time flow filter in C++? 

### ISSUE THREAD

**Issue by mczhao1977** [jadarve/lluvia#156]
I can build and run Real time flow filter example in Python succesfully. But I can't figure out how to call it using C++. Any example or documentation about this? The only c++ example is Pyramid, but it only use core library, not node.
Thanks!

**Comment by jadarve** [comment]
Hi, thanks for pointing this out. I have presented most of the examples in Python so to make them more accessible, but everything should equally be possible to code in C++.

I started [this PR](https://github.com/jadarve/lluvia/pull/157/files#diff-15ed7fb8a563ff07c45a0ddbed4ed58d48535afa3e9d05e02ea6585055abaeed) with an example on how to run the Horn and Schunck algorithm from C++ using the Node library.

The basics to use the available nodes is as follows:

```cpp
#include <iostream>
#include <lluvia/core.h>

int main(int argc, char** argv)
{

    if (argc != 2) {
        std::cout << "missing library path, use 'opticalFlowCpp <path-to-library>'" << std::endl;
        return EXIT_FAILURE;
    }

    auto libraryPath = std::string {argv[1]};

    ///////////////////////////////////////////////////////////////////////////
    // Enumerate available

    auto availableDevices = ll::Session::getAvailableDevices();
    auto selectedDevice   = availableDevices[0];

    std::cout << "------------------------------------------------------------" << std::endl;
    for (auto& device : ll::Session::getAvailableDevices()) {
        std::cout << "ID: " << device.id << " type: " << ll::deviceTypeToString(std::forward<ll::DeviceType>(device.deviceType)) << " name: " << device.name << std::endl;

        if (device.deviceType == ll::DeviceType::DiscreteGPU) {
            selectedDevice = device;
        }
    }
    std::cout << "------------------------------------------------------------" << std::endl;

    ///////////////////////////////////////////////////////////////////////////
    // Create lluvia session and load the node library

    auto sessionDescriptor = ll::SessionDescriptor {}
                                 .setDeviceDescriptor(selectedDevice)
                                 .enableDebug(true);

    auto session = std::shared_ptr<ll::Session> {ll::Session::create(sessionDescriptor)};
    session->loadLibrary(libraryPath);

    // enumerate all available node descriptors
    for (const auto& nodeDesc : session->getNodeBuilderDescriptors()) {
        std::cout << nodeDesc.name << std::endl;
    }
}
```

where `session->loadLibrary(libraryPath);` loads the `.zip` archive with all the Lua and GLSL code for the nodes. This zip archive is available at `bazel-bin/lluvia/nodes/lluvia_node_library.zip` once you build the project (for Python, the archive is packed as part of the wheel installer).

I will polish the sample code in the coming days. If you have more details on how you plan on using Lluvia, that will be very helpful.

**Comment by mczhao1977** [comment]
Hi, thanks for your info. I didn't notice the loadLibrary function before. I will give it a try and update the result here.

**Comment by jadarve** [comment]
Hi, I completed the demo in PR https://github.com/jadarve/lluvia/pull/157. The instructions to run it (Linux) are as follows:

First, build the node library target in the `lluvia` project:

```bash
bazel build //lluvia/nodes:lluvia_node_library
```

Then, run the example:

```bash
cd examples

# run the example
bazel run //opticalFlowCpp:opticalFlowCpp $(pwd)/../bazel-bin/lluvia/nodes/lluvia_node_library.zip
```

where `$(pwd)/../bazel-bin/lluvia/nodes/lluvia_node_library.zip` is the absolute path to the node library target archive containing the GLSL and Lua code that make the nodes.

The terminal output should look like:

```
------------------------------------------------------------
ID: 39520 type: IntegratedGPU name: Intel(R) UHD Graphics (TGL GT1)
ID: 9373 type: DiscreteGPU name: NVIDIA GeForce RTX 3070 Laptop GPU
ID: 0 type: CPU name: llvmpipe (LLVM 15.0.7, 256 bits)
------------------------------------------------------------
------------------------------------------------------------
Using device ID: 9373 type: DiscreteGPU name: NVIDIA GeForce RTX 3070 Laptop GPU
------------------------------------------------------------
lluvia/camera/CameraUndistort_rgba8ui
lluvia/color/BGRA2Gray
lluvia/color/HSVA2RGBA
lluvia/color/RGBA2BGRA
lluvia/color/RGBA2Gray
lluvia/color/RGBA2HSVA
lluvia/imgproc/ImageDownsampleX_r8ui
lluvia/imgproc/ImageDownsampleY_r8ui
lluvia/imgproc/ImagePyramid_r8ui
lluvia/math/normalize/ImageNormalize_uint_C1
lluvia/opticalflow/flowfilter/FlowFilter
lluvia/opticalflow/flowfilter/FlowFilterDelta
lluvia/opticalflow/flowfilter/FlowFilterSimple
lluvia/opticalflow/flowfilter/FlowPredict
lluvia/opticalflow/flowfilter/FlowPredictPayload
lluvia/opticalflow/flowfilter/FlowPredictPayloadX
lluvia/opticalflow/flowfilter/FlowPredictPayloadY
lluvia/opticalflow/flowfilter/FlowPredictX
lluvia/opticalflow/flowfilter/FlowPredictY
lluvia/opticalflow/flowfilter/FlowSmooth
lluvia/opticalflow/flowfilter/FlowUpdate
lluvia/opticalflow/flowfilter/FlowUpdateDelta
lluvia/opticalflow/flowfilter/ImageModel
lluvia/opticalflow/HornSchunck/HornSchunck
lluvia/opticalflow/HornSchunck/ImageProcessor
lluvia/opticalflow/HornSchunck/NumericIteration
lluvia/Sobel
lluvia/viz/colormap/ColorMap
lluvia/viz/colormap/ColorMap_float
lluvia/viz/colormap/ColorMap_int
lluvia/viz/colormap/ColorMap_uint
lluvia/viz/Flow2RGBA
webcam/HornSchunck
```

while there should also be two OpenCV windows: one with the input image from the webcam, and another one with the color-encoded optical flow.


![image](https://github.com/jadarve/lluvia/assets/2498576/0018046f-167a-476b-a7f7-98bbb534b693)


Let me know if you need something else, otherwise to close this issue.

**Comment by mczhao1977** [comment]
Thanks for the cpp demo. I can build and run it succefully, great work!
I have a question about the workflow of optical flow. Traditional optical flow algotithm usually accept two inputs: one for previous frame, one for current frame.  HS in Lluvia seems only accept one input. So internally it saves previous frame for current frame calculation?  I observed a little strange behavior for the first several frames:
First frame - the optical flow seems strange, is it calculated with respect to an initial black image?:
![firstFrame](https://github.com/jadarve/lluvia/assets/20310300/de728bc7-e522-45e5-89b9-4fec79209109)

Second frame - Seems better, but still has many residual
![secondFrame](https://github.com/jadarve/lluvia/assets/20310300/ca0d15fd-2fe8-4ff0-beb8-50c669ce73e4)

The test video is downloaded from https://github.com/spmallick/learnopencv/blob/master/Optical-Flow-in-OpenCV/videos/people.mp4

**Comment by jadarve** [comment]
Good catch! I will answer your question in two parts:

> I have a question about the workflow of optical flow. Traditional optical flow algotithm usually accept two inputs: one for previous frame, one for current frame. HS in Lluvia seems only accept one input. So internally it saves previous frame for current frame calculation? I observed a little strange behavior for the first several frames:

That's correct, the HS implementation stores the previous frame internally and receives the next frame to calculate the optical flow. For video processing, this approach makes sense as one consumes one frame at a time from the camera or video decoder.

Also, the HS uses the optical flow calculated at the previous time as a seed for the new calculation.

You could still use the Lluvia node for computing the optical flow for two image frames only (without memory) by increasing the number of numeric iterations of the solver. Here I used 1000 iterations for the Middlebury dataset: https://lluvia.ai/blog/2022/08/07/implementing-the-horn-and-schunck-optical-flow-algorithm/

> First frame - the optical flow seems strange, is it calculated with respect to an initial black image?:
> Second frame - Seems better, but still has many residual

That's an error in the demo app in not passing the very first image of the camera, or video, before initializing the optical flow node. PR https://github.com/jadarve/lluvia/pull/158/files fixes it

![image](https://github.com/jadarve/lluvia/assets/2498576/bf12a564-1f84-4336-868b-b733bae63a9e)


Let me know if your use case for the optical flow needs resetting the internal state after each input frame. That will require extra work.

**Comment by mczhao1977** [comment]
Thanks for your qucik answer.
I tried the newest demo app and it works fine for first several frames. But in some frames it still has strong residual:
![residualFrame](https://github.com/jadarve/lluvia/assets/20310300/e9539a77-0821-48a2-9082-42dd2beea72c)
Could you add a parameter to allow the user to reset the internal state after each input frame? The optical flow of the first frame seems good with only 20 iterations and no any seed. Thanks.

**Comment by jadarve** [comment]
PR #159 added the `clear_history` parameter to the Horn and Schunck node.  I actually set it to have the default value to 1 (i.e. clear the history after each image time step) to keep the mode easier to compare with other implementations.

![image](https://github.com/jadarve/lluvia/assets/2498576/a0a4ac17-bed1-4a88-880a-d6c680d0af67)

You probably will need to add more iterations in order to fill in textureless regions.

Let me know how it goes :smiley:.

**Comment by mczhao1977** [comment]
I tried it and works fine. Thanks!
