### ISSUE TITLE
is there something wrong in CMakeLists?

### ISSUE THREAD

**Issue by zhangsuchi** [jadarve/lluvia#59]
#################################################
# SOURCE FILES SETTINGS
#################################################
add_subdirectory(core)--------------------------->core is not exsit, you means : cpp/core ?
add_subdirectory(tools)
add_subdirectory(samples)

# creates the shaders custom target
include (cmake/shaders.cmake)

Now, there are some compilation errors with cmake...............

**Comment by jadarve** [comment]
Hi, I changed build system from CMake to Bazel a while ago, but haven't deleted the CMakeLIsts files for safety in case I'm not able to do something with Bazel.

For building the project, you can run:

```shell
CC=clang bazel build //...
CC=clang bazel build @lua//:lua_cc_library
cd python
CC=clang python3 setup.py build
```

You can check the list of dependencies in https://github.com/jadarve/lluvia/blob/master/ci/Dockerfile
