### ISSUE TITLE
Instruction for build

### ISSUE THREAD

**Issue by xEnVrE** [jadarve/lluvia#63]
Hi @jadarve,

I would like to try `lluvia`. I tried compiling using `CMake` without success as some files cannot be found.

Is there any plan on adding build and installation instruction?

Thank you!

**Comment by jadarve** [comment]
Hey @xEnVrE 

I changed the build system from CMake to Bazel a while ago, but I still have not removed the CMakeLists files.

You can follow the instructions at https://lluvia.io/en/latest/installation.html for compiling the library for Linux.

The documentation for how to actually use lluvia is lacking at the moment :( I need to do more work on that side. Check the optical flow demo to get an idea on how to use it: https://github.com/jadarve/lluvia/blob/master/samples/opticalFlow/python/opticalFlow.py

Let me know your specific case and I can help you.

Cheers.

**Comment by xEnVrE** [comment]
Hi @jadarve,

thank you for the information. I also had the possibility to try the optical flow algorithm from the old implementation [repository](https://github.com/jadarve/optical-flow-filter).
